### ISSUE TITLE
Registration is buggy. Currently I can't register.

### ISSUE THREAD

**Issue by unicodeveloper** [andela-cganga/watch-n-learn#76]
<img width="1120" alt="screen shot 2016-02-25 at 6 35 51 am" src="https://cloud.githubusercontent.com/assets/2946769/13311110/082b1dce-db8c-11e5-9276-23e638051982.png">

**Comment by andela-cganga** [comment]
@unicodeveloper I had put the wrong link.. I've fixed it, and written a test for it.
